// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_UG3FMWo2onKF5kM2LiZ1KRV5Oc9e_Q',
    appId: '1:293391192604:web:63ef5159993596e32a45d9',
    messagingSenderId: '293391192604',
    projectId: 'moneybeeapp-f72c5',
    authDomain: 'moneybeeapp-f72c5.firebaseapp.com',
    storageBucket: 'moneybeeapp-f72c5.firebasestorage.app',
    measurementId: 'G-72G20FZYG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfbYlSrrfaPNUyaWdrgMvSK-Nslm8BPc',
    appId: '1:293391192604:android:46bb72cc3809fbc62a45d9',
    messagingSenderId: '293391192604',
    projectId: 'moneybeeapp-f72c5',
    storageBucket: 'moneybeeapp-f72c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaOGpib7ijgjV61afU4PfSUGlzp3_jbF4',
    appId: '1:293391192604:ios:5b4fede963f22c0f2a45d9',
    messagingSenderId: '293391192604',
    projectId: 'moneybeeapp-f72c5',
    storageBucket: 'moneybeeapp-f72c5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaOGpib7ijgjV61afU4PfSUGlzp3_jbF4',
    appId: '1:293391192604:ios:5b4fede963f22c0f2a45d9',
    messagingSenderId: '293391192604',
    projectId: 'moneybeeapp-f72c5',
    storageBucket: 'moneybeeapp-f72c5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_UG3FMWo2onKF5kM2LiZ1KRV5Oc9e_Q',
    appId: '1:293391192604:web:8b0415bf9f5470762a45d9',
    messagingSenderId: '293391192604',
    projectId: 'moneybeeapp-f72c5',
    authDomain: 'moneybeeapp-f72c5.firebaseapp.com',
    storageBucket: 'moneybeeapp-f72c5.firebasestorage.app',
    measurementId: 'G-EZ8ZFSDDSZ',
  );
}
